export const CLAIM_ENDPOINTS = {
  list: "/v1/claims",
  detail: (id: string) => `/v1/claims/${id}`,
  submit: (id: string) => `/v1/claims/submit/${id}`,
  updateStatus: (id: string) => `/v1/claims/update-status/${id}`,
  configurations: "/v1/claims/configurations",
  export: "/v1/claims/export",
  import: "/v1/claims/import",
  importDataGuide: "/v1/claims/import-data-guide",
  claimListLimit: "/v1/claims/claim-list-limit",
  statistics: "/v1/claims/statistic-data",
  histories: "/v1/claim-histories",
  categoryForms: (id: string) => `/v1/claim-category-forms/all/${id}`,
  channelForms: (id: string) => `/v1/claim-channel-forms/all/${id}`,
} as const;
