export const AUTH_ENDPOINTS = {
  login: "/login",
  accounts: "/account",
  accountDetail: (id: string) => `/account/${id}`,
  accountAllDataPagination: "/account/all-data/pagination",
  accountAllDataDetail: (id: string) => `/account/all-data/${id}`,
  accountPartners: "/v1/account/partner",
  accountChangePassword: (id: string) => `/v1/account/${id}/change-password`,
  accountGroups: "/v1/account-groups",
  accountGroupDetail: (id: string) => `/v1/account-groups/${id}`,
  accountRoles: "/v1/account-roles",
  accountRoleDetail: (id: string) => `/v1/account-roles/${id}`,
  accountChannels: "/v1/account-channels",
  accountChannelDetail: (id: string) => `/v1/account-channels/${id}`,
  accountChannelsByAccount: (accountId: string) =>
    `/v1/account-channels/account/${accountId}`,
  accountInsurers: "/v1/account-insurers",
  accountInsurerDetail: (id: string) => `/v1/account-insurers/${id}`,
  accountInsurersByAccount: (accountId: string) =>
    `/v1/account-insurers/account/${accountId}`,
  groups: "/v1/group",
  groupDetail: (id: string) => `/v1/group/${id}`,
  groupRoles: "/v1/group-roles",
  groupRoleDetail: (id: string) => `/v1/group-roles/${id}`,
  roles: "/role",
  roleDetail: (id: string) => `/role/${id}`,
  pages: "/pages",
  pageDetail: (id: string) => `/pages/${id}`,
  permissions: "/v1/permission",
  permissionDetail: (id: string) => `/v1/permission/${id}`,
  permissionByPage: (pageId: string) => `/v1/permission/page/${pageId}`,
  rolePermissions: "/v1/role-permission",
  rolePermissionDetail: (id: string) => `/v1/role-permission/${id}`,
} as const;
