import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'react-loading-skeleton/dist/skeleton.css';
import "./globals.css";
import ClientLayout from "@/components/ui/ClientLayout";
import { Toaster } from "react-hot-toast";
import { LoadingProvider } from "@/context/loading.context";
import { NotFoundProvider } from "@/context/not-found.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Portal",
  description: "Generated by friendsure",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <NotFoundProvider>
          <LoadingProvider>
            <Toaster />
            <ClientLayout>{children}</ClientLayout>
          </LoadingProvider>
        </NotFoundProvider>
      </body>
    </html>
  );
}
